destination: ../build
future: true
highlighter: pygments
host: 0.0.0.0
markdown: redcarpet # kramdown doesn't support ``` for code blocks
markdown_ext: "md"
name: "Art Chaidarun"
permalink: /:title.html
redcarpet:
  extensions: ["smart", "strikethrough", "tables", "with_toc_data"]
url: https://chaidarun.com
